export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const SET_ENTRIES = "SET_ENTRIES";
export const SET_USER = "SET_USER";
